name: Docker Image CI

on:
  push:
    branches: 
      - main
    paths:
      - dockerfiles/golang/**
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
