name: Docker Image CI

on:
  push:
    branches: 
      - main
    paths:
      - dockerfiles/golang/**
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo "building the docker image"
