name: Docker Image CI

on:
  push:
    branches: 
      - main
    paths:
      - dockerfiles/golang/**
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        run: docker build .
