name: Docker Image CI

on:
  push:
    branches: 
      - main
    paths:
      - dockerfiles/golang/1.15-alpine-fuzz/**
  pull_request:
    branches: [ main ]

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: ./
        with:
          file: ./dockerfiles/golang/1.15-alpine-fuzz/Dockerfile
