name: Docker Image CI

on:
  push:
    branches: 
      - main
    paths:
      - dockerfiles/golang/**
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:rajesh/dockerfiles/golang/**"
          push: true
          tags: user/app:latest
